name: MT4 Cloud Compiler

on:
  workflow_dispatch:
  push:
    paths:
      - '**.mq4'
      - '**.mqh'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull MT4 compiler
        run: docker pull ghcr.io/d0whc3r/mt4-wine-compiler:master

      - name: Compile MQ4
        run: |
          set -e

          find "$GITHUB_WORKSPACE" -type f -name "*.mq4" -print0 |
          while IFS= read -r -d '' file; do

            rel="${file#$GITHUB_WORKSPACE/}"

            echo "========================================"
            echo "Compiling: $rel"
            echo "========================================"

            docker run --rm \
              --entrypoint /usr/bin/xvfb-run \
              -v "$GITHUB_WORKSPACE:/home/wine/src" \
              ghcr.io/d0whc3r/mt4-wine-compiler:master \
              -a \
              /home/wine/entrypoint.sh \
              "/home/wine/src/$rel"

          done

      - name: Check result
        if: always()
        run: |
          echo "===== EX4 ====="
          find "$GITHUB_WORKSPACE" -type f -name "*.ex4" -print || true
          echo "===== LOG ====="
          find "$GITHUB_WORKSPACE" -type f -name "*.log" -print || true

      - name: Upload EX4
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: MT4-Compiled-Files
          path: |
            **/*.ex4
            **/*.log
          if-no-files-found: warn
